# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'tekrowedding' do
pod 'AFNetworking', '~> 2.5'
pod 'ZBarSDK', '~> 1.3'
pod 'MWPhotoBrowser', '~> 1.4.0'
end

target 'tekroweddingTests' do

end

